name: CI/CD PracticaFinal

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Clonar repositorio
      uses: actions/checkout@v3

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: ✅ Ejecutar pruebas unitarias
      run: pytest test_app.py

    - name: 🐳 Instalar Docker clásico
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER
        docker --version

    - name: 🔐 Login a Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 🐳 Construir imagen Docker
      run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-holamundo:latest .

    - name: 📤 Subir imagen a Docker Hub
      run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/devops-holamundo:latest

    - name: 🚀 Desplegar en Render
      run: |
        curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
